-- Bank Comparison Data
-- Generated: 2025-11-27T01:21:31.108Z
-- Total banks: 219

-- Clear existing data (optional - comment out if you want to keep existing data)
-- TRUNCATE TABLE bank_comparison;

-- Insert bank comparison data
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('78 Finance Company Ltd', '40195', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('9mobile 9Payment Service Bank', '120001', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Abbey Mortgage Bank', '404', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Above Only MFB', '51204', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Abulesoro MFB', '51312', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Access Bank', '044', '000014', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Access Bank (Diamond)', '063', '000005', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Accion Microfinance Bank', '602', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Aella MFB', '50315', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('AG Mortgage Bank', '90077', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Ahmadu Bello University Microfinance Bank', '50036', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Airtel Smartcash PSB', '120004', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('AKU Microfinance Bank', '51336', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Akuchukwu Microfinance Bank Limited', '090561', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Al-Barakah Microfinance Bank', '50055', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('ALAT by WEMA', '035A', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Alpha Morgan Bank', '108', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Alternative bank', '000304', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Amegy Microfinance Bank', '090629', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Amju Unique MFB', '50926', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Aramoko MFB', '50083', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('ASO Savings and Loans', '401', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Assets Microfinance Bank', '50092', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Astrapolaris MFB LTD', 'MFB50094', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('AVUENEGBE MICROFINANCE BANK', '090478', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('AWACASH MICROFINANCE BANK', '51351', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('AZTEC MICROFINANCE BANK LIMITED', '51337', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Bainescredit MFB', '51229', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Banc Corp Microfinance Bank', '50117', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('BANKIT MICROFINANCE BANK LTD', '50572', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('BANKLY MFB', '51341', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Baobab Microfinance Bank', 'MFB50992', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('BellBank Microfinance Bank', '51100', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Benysta Microfinance Bank Limited', '51267', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Beststar Microfinance Bank', '50123', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('BOLD MFB', '50725', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Bosak Microfinance Bank', '650', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Bowen Microfinance Bank', '50931', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Branch International Finance Company Limited', 'FC40163', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Brent Mortgage bank', '90070', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('BuyPower MFB', '50645', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Carbon', '565', '100026', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Cashbridge Microfinance Bank Limited', '51353', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('CASHCONNECT MFB', '865', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('CEMCS Microfinance Bank', '50823', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Chanelle Microfinance Bank Limited', '50171', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Chikum Microfinance bank', '312', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Citibank Nigeria', '023', '000009', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('CITYCODE MORTAGE BANK', '070027', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Consumer Microfinance Bank', '50910', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Cool Microfinance Bank Limited', '51458', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Corestep MFB', '50204', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Coronation Merchant Bank', '559', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('County Finance Limited', 'FC40128', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Credit Direct Limited', '40119', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Crescent MFB', '51297', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Crust Microfinance Bank', '090560', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('CRUTECH MICROFINANCE BANK LTD', '50216', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Dash Microfinance Bank', '51368', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Davenport MICROFINANCE BANK', '51334', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Dillon Microfinance Bank', '51450', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Dot Microfinance Bank', '50162', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('EBSU Microfinance Bank', '50922', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Ecobank Nigeria', '050', '000010', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Ekimogun MFB', '50263', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Ekondo Microfinance Bank', '098', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('EXCEL FINANCE BANK', '090678', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Eyowo', '50126', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Fairmoney Microfinance Bank', '51318', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Fedeth MFB', '50298', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Fidelity Bank', '070', '000007', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Firmus MFB', '51314', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('First Bank of Nigeria', '011', '000016', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('First City Monument Bank', '214', '000003', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('FIRST ROYAL MICROFINANCE BANK', '090164', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('FIRSTMIDAS MFB', '51333', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('FirstTrust Mortgage Bank Nigeria', '413', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('FSDH Merchant Bank Limited', '501', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('FUTMINNA MICROFINANCE BANK', '832', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Garun Mallam MFB', 'MFB51093', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Gateway Mortgage Bank LTD', '812', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Globus Bank', '00103', '000027', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Goldman MFB', '090574', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('GoMoney', '100022', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('GOOD SHEPHERD MICROFINANCE BANK', '090664', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Goodnews Microfinance Bank', '50739', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Greenwich Merchant Bank', '562', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('GROOMING MICROFINANCE BANK', '51276', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('GTI MFB', '50368', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Guaranty Trust Bank', '058', '000013', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Hackman Microfinance Bank', '51251', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Hasal Microfinance Bank', '50383', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Hayat Trust MFB', '51364', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('HopePSB', '120002', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('IBANK Microfinance Bank', '51211', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('IBBU MFB', '51279', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Ibile Microfinance Bank', '51244', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Ibom Mortgage Bank', '90012', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Ikoyi Osun MFB', '50439', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Ilaro Poly Microfinance Bank', '50442', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Imowo MFB', '50453', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('IMPERIAL HOMES MORTAGE BANK', '415', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('INDULGE MFB', '51392', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Infinity MFB', '50457', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Infinity trust  Mortgage Bank', '070016', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('ISUA MFB', '090701', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Jaiz Bank', '301', '000006', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Kadpoly MFB', '50502', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('KANOPOLY MFB', '51308', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Kayvee Microfinance Bank', '5129', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Keystone Bank', '082', '000002', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Kolomoni MFB', '899', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)', '100025', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Kredi Money MFB LTD', '50200', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Kuda Bank', '50211', '090267', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Lagos Building Investment Company Plc.', '90052', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Letshego Microfinance Bank', '090420', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Links MFB', '50549', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Living Trust Mortgage Bank', '031', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('LOMA MFB', '50491', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Lotus Bank', '303', '000029', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Maal MFB', '51444', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('MAINSTREET MICROFINANCE BANK', '090171', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Mayfair MFB', '50563', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Mint MFB', '50304', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('MINT-FINEX MFB', '09', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Money Master PSB', '946', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Moniepoint MFB', '50515', '090405', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('MTN Momo PSB', '120003', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('MUTUAL BENEFITS MICROFINANCE BANK', '090190', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('NDCC MICROFINANCE BANK', '090679', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('NET MICROFINANCE BANK', '51361', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Nigerian Navy Microfinance Bank Limited', '51142', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Nombank MFB', '50072', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('NOVA BANK', '561', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Novus MFB', '51371', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('NPF MICROFINANCE BANK', '50629', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('NSUK MICROFINANACE BANK', '51261', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Olabisi Onabanjo University Microfinance Bank', '50689', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('OLUCHUKWU MICROFINANCE BANK LTD', '50697', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('OPay Digital Services Limited (OPay)', '999992', '100004', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Optimus Bank Limited', '107', '000036', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Paga', '100002', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('PalmPay', '999991', '100033', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Parallex Bank', '104', '000030', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Parkway - ReadyCash', '311', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('PATHFINDER MICROFINANCE BANK LIMITED', '090680', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Paystack-Titan', '100039', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Peace Microfinance Bank', '50743', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('PECANTRUST MICROFINANCE BANK LIMITED', '51226', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Personal Trust MFB', '51146', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Petra Mircofinance Bank Plc', '50746', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Pettysave MFB', 'MFB51452', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('PFI FINANCE COMPANY LIMITED', '050021', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Platinum Mortgage Bank', '268', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Pocket App', '00716', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Polaris Bank', '076', '000008', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Polyunwana MFB', '50864', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('PremiumTrust Bank', '105', '000031', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Prospa Capital Microfinance Bank', '50739', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('PROSPERIS FINANCE LIMITED', '050023', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Providus Bank', '101', '000023', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('QuickFund MFB', '51293', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Rand Merchant Bank', '502', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('RANDALPHA MICROFINANCE BANK', '090496', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Refuge Mortgage Bank', '90067', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('REHOBOTH MICROFINANCE BANK', '50761', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Rephidim Microfinance Bank', '50994', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Rigo Microfinance Bank Limited', '51286', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('ROCKSHIELD MICROFINANCE BANK', '50767', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Rubies MFB', '125', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Safe Haven MFB', '51113', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('SAGE GREY FINANCE LIMITED', '40165', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Shield MFB', '50582', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Signature Bank Ltd', '106', '000034', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Solid Allianze MFB', '51062', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Solid Rock MFB', '50800', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Sparkle Microfinance Bank', '51310', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Springfield Microfinance Bank', '51429', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Stanbic IBTC Bank', '221', '000012', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Standard Chartered Bank', '068', '000021', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('STANFORD MICROFINANCE BANK', '090162', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('STATESIDE MICROFINANCE BANK', '50809', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('STB Mortgage Bank', '070022', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Stellas MFB', '51253', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Sterling Bank', '232', '000001', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Summit Bank', '00305', '080030', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Suntrust Bank', '100', '000022', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Supreme MFB', '50968', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('TAJ Bank', '302', '000026', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Tangerine Money', '51269', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('TENN', '51403', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Think Finance Microfinance Bank', '677', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Titan Bank', '102', '000025', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('TransPay MFB', '090708', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('TRUSTBANC J6 MICROFINANCE BANK', '51118', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('U&C Microfinance Bank Ltd (U AND C MFB)', '50840', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('UCEE MFB', '090706', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Uhuru MFB', '51322', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Ultraviolet Microfinance Bank', '51080', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Unaab Microfinance Bank Limited', '50870', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('UNIABUJA MFB', '51447', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Unical MFB', '50871', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Unilag Microfinance Bank', '51316', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('UNIMAID MICROFINANCE BANK', '50875', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Union Bank of Nigeria', '032', '000018', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('United Bank For Africa', '033', '000004', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Unity Bank', '215', '000011', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Uzondu Microfinance Bank Awka Anambra State', '50894', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Vale Finance Limited', '050020', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('VFD Microfinance Bank Limited', '566', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Waya Microfinance Bank', '51355', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Wema Bank', '035', '000017', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Weston Charis MFB', '51386', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Xpress Wallet', '100040', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Yes MFB', '594', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Zap', '00zap', NULL, 'Paystack Only', 'Paystack');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Zenith Bank', '057', '000015', 'Available in SafeHaven', 'SafeHaven');
INSERT INTO bank_comparison (bank_name, paystack_code, safehaven_code, status, provider) VALUES ('Zitra MFB', '51373', NULL, 'Paystack Only', 'Paystack');

-- Verify the data
SELECT 
  status,
  COUNT(*) as count
FROM bank_comparison
GROUP BY status
ORDER BY status;
