/**
 * Reconcile payout plans (cron every 15m)
 *
 * 1) Auto-fix stuck progress via reconcile_stuck_payout_progress
 * 2) List failed installments needing manual bank pay / ops
 * 3) Scan wallet/plan/payout accuracy anomalies + unreimbursed debits (no money movement)
 * 4) Email support@planmoni.com + sebastine@planmoni.com (6h dedup)
 * 5) Log run to payout_reconciliation_runs
 */

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const SUPPORT_TO = ["support@planmoni.com", "sebastine@planmoni.com"];
const EMAIL_DEDUP_HOURS = 6;

type ManualRow = {
  plan_id: string;
  user_id: string;
  plan_name: string;
  amount: number | string;
  next_payout_date: string;
  ap_id: string;
  ap_status: string;
  transfer_reference: string | null;
  reason: string;
  suggested_action: string;
};

type AccuracyFinding = {
  finding_key: string;
  signal: string;
  severity: string;
  user_id: string | null;
  plan_id: string | null;
  ap_id: string | null;
  email: string | null;
  summary: string;
  details: Record<string, unknown>;
};

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatAmount(amount: number | string): string {
  const n = typeof amount === "number" ? amount : Number(amount);
  if (!Number.isFinite(n)) return String(amount);
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    maximumFractionDigits: 2,
  }).format(n);
}

function buildManualEmailHtml(rows: ManualRow[]): string {
  const trs = rows
    .map((r) => {
      return `<tr>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.plan_name || "")}</td>
        <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:12px;">${escapeHtml(r.plan_id)}</td>
        <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:12px;">${escapeHtml(r.user_id)}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(formatAmount(r.amount))}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.next_payout_date || "")}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.ap_status || "")}</td>
        <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:12px;">${escapeHtml(r.transfer_reference || "—")}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.reason || "")}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.suggested_action || "")}</td>
      </tr>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
<body style="font-family:system-ui,-apple-system,sans-serif;color:#111;">
  <h2>[Planmoni] Payouts needing manual action</h2>
  <p>${rows.length} installment(s) are past due and blocked from auto-payout. Please review and pay/complete manually where needed.</p>
  <table style="border-collapse:collapse;width:100%;font-size:13px;">
    <thead>
      <tr style="background:#f5f5f5;">
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Plan</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Plan ID</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">User ID</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Amount</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Next payout</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">AP status</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Transfer ref</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Reason</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Suggested action</th>
      </tr>
    </thead>
    <tbody>${trs}</tbody>
  </table>
  <p style="margin-top:16px;color:#555;font-size:12px;">
    Auto-generated by <code>reconcile-payout-plans</code>. Same AP set is not re-emailed within ${EMAIL_DEDUP_HOURS} hours.
  </p>
</body>
</html>`;
}

function sortedApKey(apIds: string[]): string {
  return [...apIds].sort().join(",");
}

function sortedFindingKey(keys: string[]): string {
  return [...keys].sort().join(",");
}

function severityRank(severity: string): number {
  if (severity === "critical") return 0;
  if (severity === "warning") return 1;
  return 2;
}

function buildAccuracyEmailHtml(findings: AccuracyFinding[]): string {
  const sorted = [...findings].sort(
    (a, b) =>
      severityRank(a.severity) - severityRank(b.severity) ||
      a.signal.localeCompare(b.signal)
  );

  const trs = sorted
    .map((f) => {
      return `<tr>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(f.severity)}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(f.signal)}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(f.email || "—")}</td>
        <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:12px;">${escapeHtml(f.user_id || "—")}</td>
        <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:12px;">${escapeHtml(f.plan_id || "—")}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(f.summary)}</td>
      </tr>`;
    })
    .join("");

  const criticalCount = findings.filter((f) => f.severity === "critical").length;

  return `<!DOCTYPE html>
<html>
<body style="font-family:system-ui,-apple-system,sans-serif;color:#111;">
  <h2>[Planmoni] Payout accuracy anomalies detected</h2>
  <p>${findings.length} finding(s) — ${criticalCount} critical. Review before retrying payouts or adjusting wallets.</p>
  <p style="color:#555;font-size:13px;">Run <code>SELECT jsonb_pretty(monitor_user('&lt;user_id&gt;'))</code> for per-user drill-down. Do not auto-retry users with duplicate refs or overpay signals.</p>
  <table style="border-collapse:collapse;width:100%;font-size:13px;">
    <thead>
      <tr style="background:#f5f5f5;">
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Severity</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Signal</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Email</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">User ID</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Plan ID</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Summary</th>
      </tr>
    </thead>
    <tbody>${trs}</tbody>
  </table>
  <p style="margin-top:16px;color:#555;font-size:12px;">
    Auto-generated by <code>reconcile-payout-plans</code>. Same finding set is not re-emailed within ${EMAIL_DEDUP_HOURS} hours.
  </p>
</body>
</html>`;
}

async function sendSupportEmail(
  supabaseUrl: string,
  serviceKey: string,
  subject: string,
  html: string
): Promise<{ ok: boolean; status?: number; errText?: string }> {
  const emailRes = await fetch(`${supabaseUrl}/functions/v1/send-email`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${serviceKey}`,
    },
    body: JSON.stringify({
      to: SUPPORT_TO,
      subject,
      html,
    }),
  });

  if (emailRes.ok) {
    return { ok: true };
  }

  const errText = await emailRes.text();
  return { ok: false, status: emailRes.status, errText };
}

function wasRecentlyEmailed(
  recentRuns: Array<{ details: unknown }>,
  compareKey: string,
  extractKeys: (details: Record<string, unknown>) => string[] | undefined
): boolean {
  return recentRuns.some((run) => {
    const details = run.details as Record<string, unknown> | null;
    const keys = details ? extractKeys(details) : undefined;
    if (!keys || !Array.isArray(keys)) return false;
    return sortedFindingKey(keys) === compareKey;
  });
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!supabaseUrl || !serviceKey) {
      throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
    }

    const supabase = createClient(supabaseUrl, serviceKey);

    const { data: fixResult, error: fixError } = await supabase.rpc(
      "reconcile_stuck_payout_progress",
      { p_limit: 100 }
    );
    if (fixError) {
      console.error("reconcile_stuck_payout_progress error:", fixError);
      throw fixError;
    }

    const fixedCount =
      typeof fixResult?.fixed_count === "number" ? fixResult.fixed_count : 0;

    const { data: manualRows, error: manualError } = await supabase.rpc(
      "list_payouts_needing_manual_action"
    );
    if (manualError) {
      console.error("list_payouts_needing_manual_action error:", manualError);
      throw manualError;
    }

    const manuals = (manualRows || []) as ManualRow[];
    const manualCount = manuals.length;
    const apIds = manuals.map((r) => r.ap_id).filter(Boolean);
    const apKey = sortedApKey(apIds);

    const { data: accuracyRows, error: accuracyError } = await supabase.rpc(
      "scan_payout_accuracy_anomalies",
      {
        p_since: "2026-08-01T00:00:00+00:00",
        p_limit: 100,
      }
    );
    if (accuracyError) {
      console.error("scan_payout_accuracy_anomalies error:", accuracyError);
      throw accuracyError;
    }

    const { data: unreimbursedRows, error: unreimbursedError } =
      await supabase.rpc("list_failed_unrefunded_payout_debits", {
        p_since: "2026-08-01T00:00:00+00:00",
        p_limit: 50,
      });
    if (unreimbursedError) {
      console.warn(
        "list_failed_unrefunded_payout_debits error:",
        unreimbursedError
      );
    }

    const accuracyFindings = [
      ...((accuracyRows || []) as AccuracyFinding[]),
      ...((unreimbursedRows || []) as AccuracyFinding[]),
    ];
    const accuracyCount = accuracyFindings.length;
    const findingKeys = accuracyFindings.map((f) => f.finding_key).filter(Boolean);
    const accuracyKey = sortedFindingKey(findingKeys);

    const since = new Date(
      Date.now() - EMAIL_DEDUP_HOURS * 60 * 60 * 1000
    ).toISOString();

    const { data: recentRuns, error: recentErr } = await supabase
      .from("payout_reconciliation_runs")
      .select("details, email_sent, ran_at")
      .eq("email_sent", true)
      .gte("ran_at", since)
      .order("ran_at", { ascending: false })
      .limit(30);

    if (recentErr) {
      console.warn("dedup lookup failed:", recentErr);
    }

    const recentEmailedRuns = recentRuns || [];

    let manualEmailSent = false;
    let manualEmailSkippedReason: string | null = null;

    if (manualCount > 0) {
      const alreadyEmailed = wasRecentlyEmailed(
        recentEmailedRuns,
        apKey,
        (d) => d.emailed_ap_ids as string[] | undefined
      );

      if (alreadyEmailed) {
        manualEmailSkippedReason = `same_ap_set_emailed_within_${EMAIL_DEDUP_HOURS}h`;
        console.log("Skipping manual payout email:", manualEmailSkippedReason);
      } else {
        const result = await sendSupportEmail(
          supabaseUrl,
          serviceKey,
          `[Planmoni] ${manualCount} payout(s) need manual action`,
          buildManualEmailHtml(manuals)
        );

        if (result.ok) {
          manualEmailSent = true;
          console.log("Support email sent for", manualCount, "manual payout(s)");
        } else {
          console.error("send-email failed:", result.status, result.errText);
          manualEmailSkippedReason = `send_email_failed_${result.status}`;
        }
      }
    }

    let accuracyEmailSent = false;
    let accuracyEmailSkippedReason: string | null = null;

    if (accuracyCount > 0) {
      const alreadyEmailed = wasRecentlyEmailed(
        recentEmailedRuns,
        accuracyKey,
        (d) => d.emailed_accuracy_keys as string[] | undefined
      );

      if (alreadyEmailed) {
        accuracyEmailSkippedReason = `same_accuracy_set_emailed_within_${EMAIL_DEDUP_HOURS}h`;
        console.log("Skipping accuracy email:", accuracyEmailSkippedReason);
      } else {
        const criticalCount = accuracyFindings.filter(
          (f) => f.severity === "critical"
        ).length;
        const result = await sendSupportEmail(
          supabaseUrl,
          serviceKey,
          `[Planmoni] ${accuracyCount} payout accuracy issue(s) (${criticalCount} critical)`,
          buildAccuracyEmailHtml(accuracyFindings)
        );

        if (result.ok) {
          accuracyEmailSent = true;
          console.log(
            "Accuracy email sent for",
            accuracyCount,
            "finding(s)"
          );
        } else {
          console.error("accuracy send-email failed:", result.status, result.errText);
          accuracyEmailSkippedReason = `send_email_failed_${result.status}`;
        }
      }
    }

    const details = {
      fixed: fixResult?.fixed ?? [],
      errors: fixResult?.errors ?? [],
      user_ids_recalculated: fixResult?.user_ids_recalculated ?? [],
      manual: manuals,
      emailed_ap_ids: manualEmailSent ? apIds : [],
      manual_email_skipped_reason: manualEmailSkippedReason,
      accuracy: accuracyFindings,
      accuracy_count: accuracyCount,
      emailed_accuracy_keys: accuracyEmailSent ? findingKeys : [],
      accuracy_email_skipped_reason: accuracyEmailSkippedReason,
      email_skipped_reason: manualEmailSkippedReason ?? accuracyEmailSkippedReason,
    };

    const { data: runRow, error: insertErr } = await supabase
      .from("payout_reconciliation_runs")
      .insert({
        fixed_count: fixedCount,
        manual_count: manualCount,
        details,
        email_sent: manualEmailSent || accuracyEmailSent,
      })
      .select("id")
      .single();

    if (insertErr) {
      console.error("Failed to insert payout_reconciliation_runs:", insertErr);
    }

    if (runRow?.id && accuracyCount > 0) {
      const { error: upsertErr } = await supabase.rpc(
        "upsert_payout_accuracy_findings",
        {
          p_findings: accuracyFindings,
          p_run_id: runRow.id,
        }
      );
      if (upsertErr) {
        console.error("upsert_payout_accuracy_findings error:", upsertErr);
      }
    }

    const summary = {
      success: true,
      fixed_count: fixedCount,
      manual_count: manualCount,
      accuracy_count: accuracyCount,
      manual_email_sent: manualEmailSent,
      accuracy_email_sent: accuracyEmailSent,
      email_sent: manualEmailSent || accuracyEmailSent,
      manual_email_skipped_reason: manualEmailSkippedReason,
      accuracy_email_skipped_reason: accuracyEmailSkippedReason,
    };

    console.log("reconcile-payout-plans summary:", JSON.stringify(summary));

    return new Response(JSON.stringify(summary), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("reconcile-payout-plans error:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : String(error),
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
