/**
 * Reconcile payout plans (cron every 15m)
 *
 * 1) Auto-fix stuck progress via reconcile_stuck_payout_progress
 * 2) List failed installments needing manual bank pay / ops
 * 3) Email support@planmoni.com + sebastine@planmoni.com (6h dedup on ap_ids)
 * 4) Log run to payout_reconciliation_runs
 */

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const SUPPORT_TO = ["support@planmoni.com", "sebastine@planmoni.com"];
const EMAIL_DEDUP_HOURS = 6;

type ManualRow = {
  plan_id: string;
  user_id: string;
  plan_name: string;
  amount: number | string;
  next_payout_date: string;
  ap_id: string;
  ap_status: string;
  transfer_reference: string | null;
  reason: string;
  suggested_action: string;
};

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatAmount(amount: number | string): string {
  const n = typeof amount === "number" ? amount : Number(amount);
  if (!Number.isFinite(n)) return String(amount);
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    maximumFractionDigits: 2,
  }).format(n);
}

function buildManualEmailHtml(rows: ManualRow[]): string {
  const trs = rows
    .map((r) => {
      return `<tr>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.plan_name || "")}</td>
        <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:12px;">${escapeHtml(r.plan_id)}</td>
        <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:12px;">${escapeHtml(r.user_id)}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(formatAmount(r.amount))}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.next_payout_date || "")}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.ap_status || "")}</td>
        <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:12px;">${escapeHtml(r.transfer_reference || "—")}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.reason || "")}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(r.suggested_action || "")}</td>
      </tr>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
<body style="font-family:system-ui,-apple-system,sans-serif;color:#111;">
  <h2>[Planmoni] Payouts needing manual action</h2>
  <p>${rows.length} installment(s) are past due and blocked from auto-payout. Please review and pay/complete manually where needed.</p>
  <table style="border-collapse:collapse;width:100%;font-size:13px;">
    <thead>
      <tr style="background:#f5f5f5;">
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Plan</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Plan ID</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">User ID</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Amount</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Next payout</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">AP status</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Transfer ref</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Reason</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Suggested action</th>
      </tr>
    </thead>
    <tbody>${trs}</tbody>
  </table>
  <p style="margin-top:16px;color:#555;font-size:12px;">
    Auto-generated by <code>reconcile-payout-plans</code>. Same AP set is not re-emailed within ${EMAIL_DEDUP_HOURS} hours.
  </p>
</body>
</html>`;
}

function sortedApKey(apIds: string[]): string {
  return [...apIds].sort().join(",");
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!supabaseUrl || !serviceKey) {
      throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
    }

    const supabase = createClient(supabaseUrl, serviceKey);

    const { data: fixResult, error: fixError } = await supabase.rpc(
      "reconcile_stuck_payout_progress",
      { p_limit: 100 }
    );
    if (fixError) {
      console.error("reconcile_stuck_payout_progress error:", fixError);
      throw fixError;
    }

    const fixedCount =
      typeof fixResult?.fixed_count === "number" ? fixResult.fixed_count : 0;

    const { data: manualRows, error: manualError } = await supabase.rpc(
      "list_payouts_needing_manual_action"
    );
    if (manualError) {
      console.error("list_payouts_needing_manual_action error:", manualError);
      throw manualError;
    }

    const manuals = (manualRows || []) as ManualRow[];
    const manualCount = manuals.length;
    const apIds = manuals.map((r) => r.ap_id).filter(Boolean);
    const apKey = sortedApKey(apIds);

    let emailSent = false;
    let emailSkippedReason: string | null = null;

    if (manualCount > 0) {
      const since = new Date(
        Date.now() - EMAIL_DEDUP_HOURS * 60 * 60 * 1000
      ).toISOString();

      const { data: recentRuns, error: recentErr } = await supabase
        .from("payout_reconciliation_runs")
        .select("details, email_sent, ran_at")
        .eq("email_sent", true)
        .gte("ran_at", since)
        .order("ran_at", { ascending: false })
        .limit(20);

      if (recentErr) {
        console.warn("dedup lookup failed:", recentErr);
      }

      const alreadyEmailed = (recentRuns || []).some((run) => {
        const emailed =
          (run.details as { emailed_ap_ids?: string[] } | null)?.emailed_ap_ids;
        if (!emailed || !Array.isArray(emailed)) return false;
        return sortedApKey(emailed) === apKey;
      });

      if (alreadyEmailed) {
        emailSkippedReason = `same_ap_set_emailed_within_${EMAIL_DEDUP_HOURS}h`;
        console.log("Skipping support email:", emailSkippedReason);
      } else {
        const emailRes = await fetch(`${supabaseUrl}/functions/v1/send-email`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${serviceKey}`,
          },
          body: JSON.stringify({
            to: SUPPORT_TO,
            subject: `[Planmoni] ${manualCount} payout(s) need manual action`,
            html: buildManualEmailHtml(manuals),
          }),
        });

        if (emailRes.ok) {
          emailSent = true;
          console.log(
            "Support email sent for",
            manualCount,
            "manual payout(s)"
          );
        } else {
          const errText = await emailRes.text();
          console.error("send-email failed:", emailRes.status, errText);
          emailSkippedReason = `send_email_failed_${emailRes.status}`;
        }
      }
    }

    const details = {
      fixed: fixResult?.fixed ?? [],
      errors: fixResult?.errors ?? [],
      user_ids_recalculated: fixResult?.user_ids_recalculated ?? [],
      manual: manuals,
      emailed_ap_ids: emailSent ? apIds : [],
      email_skipped_reason: emailSkippedReason,
    };

    const { error: insertErr } = await supabase
      .from("payout_reconciliation_runs")
      .insert({
        fixed_count: fixedCount,
        manual_count: manualCount,
        details,
        email_sent: emailSent,
      });

    if (insertErr) {
      console.error("Failed to insert payout_reconciliation_runs:", insertErr);
    }

    const summary = {
      success: true,
      fixed_count: fixedCount,
      manual_count: manualCount,
      email_sent: emailSent,
      email_skipped_reason: emailSkippedReason,
    };

    console.log("reconcile-payout-plans summary:", JSON.stringify(summary));

    return new Response(JSON.stringify(summary), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("reconcile-payout-plans error:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : String(error),
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
