/**
 * scan-user-risk (cron hourly)
 *
 * Detect → alert → restrict (PND for critical only).
 * Does NOT credit wallets, refund, or mutate payouts.
 *
 * 1) collect_user_risk_signals (SQL rules)
 * 2) upsert_user_risk_event per finding
 * 3) critical + new → set profiles.post_no_debit
 * 4) email ops (6h dedup)
 * 5) log fraud_scan_runs
 */

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const SUPPORT_TO = ["support@planmoni.com", "sebastine@planmoni.com"];
const EMAIL_DEDUP_HOURS = 6;

type RiskSignal = {
  user_id: string | null;
  signal: string;
  severity: string;
  summary: string;
  details: Record<string, unknown>;
  dedupe_key: string;
};

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function sortedKey(keys: string[]): string {
  return [...keys].sort().join("|");
}

async function sendSupportEmail(
  supabaseUrl: string,
  serviceKey: string,
  subject: string,
  html: string
): Promise<{ ok: boolean; status?: number; errText?: string }> {
  const emailRes = await fetch(`${supabaseUrl}/functions/v1/send-email`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${serviceKey}`,
    },
    body: JSON.stringify({ to: SUPPORT_TO, subject, html }),
  });
  if (emailRes.ok) return { ok: true };
  return { ok: false, status: emailRes.status, errText: await emailRes.text() };
}

function buildEmailHtml(
  signals: Array<RiskSignal & { action_taken?: string; email?: string | null }>
): string {
  const critical = signals.filter((s) => s.severity === "critical");
  const warning = signals.filter((s) => s.severity === "warning");
  const rows = signals
    .map(
      (s) => `<tr>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(s.severity)}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(s.signal)}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(s.email || s.user_id || "—")}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(s.action_taken || "none")}</td>
        <td style="padding:8px;border:1px solid #ddd;">${escapeHtml(s.summary)}</td>
        <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:11px;">${escapeHtml(s.dedupe_key)}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<body style="font-family:system-ui,-apple-system,sans-serif;color:#111;">
  <h2>[Planmoni] User risk / fraud scan</h2>
  <p>${critical.length} critical, ${warning.length} warning. Critical users may have <code>post_no_debit</code> set automatically.</p>
  <p style="font-size:13px;color:#555;">Drill-down: <code>SELECT jsonb_pretty(monitor_user('&lt;user_id&gt;'));</code></p>
  <table style="border-collapse:collapse;width:100%;font-size:13px;">
    <thead>
      <tr style="background:#f5f5f5;">
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Severity</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Signal</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">User</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Action</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Summary</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left;">Dedupe</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <p style="margin-top:16px;color:#555;font-size:12px;">
    Auto-generated by <code>scan-user-risk</code>. Same finding set not re-emailed within ${EMAIL_DEDUP_HOURS}h.
    Clear PND manually after review — see docs/FRAUD_ACTIVITY.md.
  </p>
</body>
</html>`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!supabaseUrl || !serviceKey) {
      throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
    }

    const supabase = createClient(supabaseUrl, serviceKey);

    const { data: rawSignals, error: scanErr } = await supabase.rpc(
      "collect_user_risk_signals",
      {
        p_lookback_hours: 72,
        p_pass_through_min: 100000,
        p_pass_through_window_hours: 6,
        p_dest_velocity_count: 3,
        p_dest_velocity_hours: 24,
        p_high_payout_min: 100000,
        p_locked_delta_min: 100,
      }
    );

    if (scanErr) {
      console.error("collect_user_risk_signals error:", scanErr);
      throw scanErr;
    }

    const signals = (rawSignals || []) as RiskSignal[];
    const enriched: Array<
      RiskSignal & { action_taken: string; email?: string | null; event_id?: string }
    > = [];

    let pndApplied = 0;
    let criticalCount = 0;

    for (const s of signals) {
      if (s.severity === "critical") criticalCount += 1;

      const { data: eventId, error: upsertErr } = await supabase.rpc(
        "upsert_user_risk_event",
        {
          p_user_id: s.user_id,
          p_signal: s.signal,
          p_severity: s.severity,
          p_summary: s.summary,
          p_details: s.details || {},
          p_dedupe_key: s.dedupe_key,
        }
      );

      if (upsertErr) {
        console.warn("upsert_user_risk_event failed:", upsertErr, s.dedupe_key);
        continue;
      }

      let actionTaken = "none";

      // Critical → auto PND (do not clear existing PND; do not touch wallet)
      if (s.severity === "critical" && s.user_id) {
        const { data: profile } = await supabase
          .from("profiles")
          .select("id, email, post_no_debit")
          .eq("id", s.user_id)
          .maybeSingle();

        if (profile && !profile.post_no_debit) {
          const { error: pndErr } = await supabase
            .from("profiles")
            .update({
              post_no_debit: true,
              post_no_debit_reason: `auto:${s.signal} — ${s.summary}`.slice(0, 500),
              post_no_debit_at: new Date().toISOString(),
              post_no_debit_by: "scan-user-risk",
            })
            .eq("id", s.user_id);

          if (pndErr) {
            console.warn("PND update failed:", pndErr, s.user_id);
          } else {
            actionTaken = "pnd";
            pndApplied += 1;
            await supabase
              .from("user_risk_events")
              .update({ action_taken: "pnd" })
              .eq("id", eventId);
          }
        } else if (profile?.post_no_debit) {
          actionTaken = "noted";
          await supabase
            .from("user_risk_events")
            .update({ action_taken: "noted" })
            .eq("id", eventId);
        }

        enriched.push({
          ...s,
          action_taken: actionTaken,
          email: profile?.email ?? null,
          event_id: eventId as string,
        });
      } else {
        let email: string | null = null;
        if (s.user_id) {
          const { data: profile } = await supabase
            .from("profiles")
            .select("email")
            .eq("id", s.user_id)
            .maybeSingle();
          email = profile?.email ?? null;
        }
        enriched.push({
          ...s,
          action_taken: actionTaken,
          email,
          event_id: eventId as string,
        });
      }
    }

    const alertSignals = enriched.filter(
      (s) => s.severity === "critical" || s.severity === "warning"
    );
    const findingKeys = alertSignals.map((s) => s.dedupe_key);
    const compareKey = sortedKey(findingKeys);

    const dedupSince = new Date(
      Date.now() - EMAIL_DEDUP_HOURS * 60 * 60 * 1000
    ).toISOString();

    const { data: recentRuns } = await supabase
      .from("fraud_scan_runs")
      .select("details, email_sent, ran_at")
      .eq("email_sent", true)
      .gte("ran_at", dedupSince)
      .order("ran_at", { ascending: false })
      .limit(20);

    const alreadyEmailed = (recentRuns || []).some((run) => {
      const details = run.details as Record<string, unknown> | null;
      const keys = details?.emailed_dedupe_keys;
      if (!Array.isArray(keys)) return false;
      return sortedKey(keys as string[]) === compareKey;
    });

    let emailSent = false;
    let emailSkippedReason: string | null = null;

    if (alertSignals.length === 0) {
      emailSkippedReason = "no_findings";
    } else if (alreadyEmailed) {
      emailSkippedReason = `same_finding_set_emailed_within_${EMAIL_DEDUP_HOURS}h`;
    } else {
      const result = await sendSupportEmail(
        supabaseUrl,
        serviceKey,
        `[Planmoni] Risk scan: ${alertSignals.length} signal(s) (${criticalCount} critical)`,
        buildEmailHtml(alertSignals)
      );
      if (result.ok) {
        emailSent = true;
        const nowIso = new Date().toISOString();
        for (const s of alertSignals) {
          if (s.event_id) {
            await supabase
              .from("user_risk_events")
              .update({ emailed_at: nowIso })
              .eq("id", s.event_id)
              .is("emailed_at", null);
          }
        }
      } else {
        emailSkippedReason = `send_email_failed_${result.status}`;
        console.error("scan-user-risk email failed:", result.errText);
      }
    }

    const details = {
      emailed_dedupe_keys: emailSent ? findingKeys : [],
      email_skipped_reason: emailSkippedReason,
      signals: alertSignals.map((s) => ({
        dedupe_key: s.dedupe_key,
        signal: s.signal,
        severity: s.severity,
        user_id: s.user_id,
        action_taken: s.action_taken,
        summary: s.summary,
      })),
      note: "detect_alert_pnd_no_money_movement",
    };

    const { error: insertErr } = await supabase.from("fraud_scan_runs").insert({
      signals_found: alertSignals.length,
      critical_count: criticalCount,
      pnd_applied: pndApplied,
      email_sent: emailSent,
      details,
    });

    if (insertErr) {
      console.error("fraud_scan_runs insert failed:", insertErr);
    }

    const summary = {
      success: true,
      signals_found: alertSignals.length,
      critical_count: criticalCount,
      pnd_applied: pndApplied,
      email_sent: emailSent,
      email_skipped_reason: emailSkippedReason,
    };
    console.log("scan-user-risk summary:", JSON.stringify(summary));

    return new Response(JSON.stringify(summary), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("scan-user-risk error:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : String(error),
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
